### PR TITLE
Updating new link for README.md

### PR DESCRIPTION
**Pull request by tedblob**
Request you to review the link and approve

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds good; you may want to rebase against 2.14 however as that is the default branch.

**Comment by tedblob** [comment]
Thank you, Dr. Jackson for your response. 
I see 2.14 for other Jackson library projects. However, no other branches are visible in this Jackson-docs repository apart from the master. 
Can you please guide

**Comment by cowtowncoder** [comment]
@tedblob Ah! Sorry, my bad, you are right. Will merge.

**Comment by tedblob** [comment]
Thank you Dr.Jackson

**Pull request merged**
